version: '3.8'

services:
  server: 
    image: blog-backend-dev
    build:
      context: . 
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - app_data:/usr/src/app     
    ports:
      - 5000:3000      
volumes:  
  app_data: