services:
  app:
    image: todo-front
    build:
      context: . 
      dockerfile: todo-frontend/Dockerfile 
    volumes:
      - ./:/usr/src/app
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    container_name: todo-front
  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-reverse-proxy
    depends_on:
      - app #

  server: 
    image: todo-back
    build:
      context: . 
      dockerfile: todo-backend/Dockerfile
    volumes:
      - ./:/usr/src/app
      - app_data:/usr/src/app
    environment:
      - REDIS_URL= redis://redis:6379
      - MONGO_URL= mongodb://the_username:the_password@mongo:27017/the_database

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    image: redis    
    ports:
    - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./redis_data:/data
      
volumes:
  mongo_data:
  app_data: