version: '3.8'

services:
  app:
    image: blog-front-dev
    build:
      context: . 
      dockerfile: frontend/dev.Dockerfile 
    volumes:      
      - ./:/usr/src/app
      - app_data:/usr/src/app 
    container_name: blog-front-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: blog-app-reverse-proxy
    depends_on:
      - app

  server: 
    image: blog-back-dev   
    build:
      context: . 
      dockerfile: backend/dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - server_data:/usr/src/app
     
volumes:
  app_data:
  server_data: